boolTestKey: true
numberTestKey: 1
stringTestKey: 'string'

rollbar:
  accessToken: 'ROLLBAR_ACCESS_TOKEN'
  env: 'ROLLBAR_ENV'

jwt:
  token: 'test_auth_token'

communication:
  services: ['twilio', 'sendgrid']

twilio:
  verify:
    accountSid: 'AC.TWILIO_ACCOUNT_SID'
    authToken: 'TWILIO_AUTH_TOKEN'
  messaging:
    messagingServiceSid: 'TWILIO_MESSAGING_SERVICE_SID'

sendgridApiKey: 'SG.SENDGRID_API_KEY'

mongoDb:
  uri: 'mongodb://127.0.0.1:27017/todo'

server:
  port: '8080'

public:
  env: 'testing'
